### ISSUE TITLE
Solution for Zig Zag and reverse level order traversal 

### ISSUE THREAD

**Issue by palaksharma12** [jrijul1201/CPP_Soln#222]

**Comment by palaksharma12** [comment]
Please assign the following problems :
https://www.interviewbit.com/problems/zigzag-level-order-traversal-bt/
https://www.interviewbit.com/problems/reverse-level-order/

**Comment by ayushnautiyal1110** [comment]
Hi . I want to contribute please assign this to me @palaksharma12

**Comment by jrijul1201** [comment]
@ayushnautiyal1110 
Pls, solve issues that have been assigned to you directly. If you want to work on an issue, then feel free to create one and then ask for an assignment.
